name: Validate template

description: Validate ADF template

inputs:
  path:
    required: true
    description: Project root
  directory:
    required: false
    description: Template directory

runs:
  using: composite
  steps:
    - name: Setup Deno environment
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Validate template
      id: validate-template
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        ACTION_PATH: ${{ github.action_path }}
      shell: bash
      run: |
        result=$(deno run --allow-read "${ACTION_PATH}/src/main.ts" "${INPUT_PATH}" "${INPUT_DIRECTORY}")
        # Parse JSON and extract status and detail separately
        status=$(echo "$result" | jq -r '.status')
        detail=$(echo "$result" | jq -r '.detail')
        # Print validation result
        echo "::group::Validation Result"
        echo "Status: ${status}"
        echo "Detail:"
        echo "$detail"
        echo "::endgroup::"
        # If status is not 0, fail the action
        if [ "$status" != "0" ]; then
          echo "::error::Template validation failed"
          echo "$detail"
          exit 1
        fi
