name: Validate template

description: Validate ADF template

inputs:
  path:
    required: true
    description: Project root
  directory:
    required: false
    description: Template directory

outputs:
  status:
    description: Validate status
    value: $VALIDATE_STATUS
  detail:
    description: Validate detail
    value: $VALIDATE_DETAIL

runs:
  using: composite
  steps:
    - name: Setup Deno environment
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Validate template
      id: validate-template
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        ACTION_PATH: ${{ github.action_path }}
      shell: bash
      run: |
        result=$(deno run --allow-read "${ACTION_PATH}/src/main.ts" "${INPUT_PATH}" "${INPUT_DIRECTORY}")
        # Parse JSON and extract status and detail separately
        status=$(echo "$result" | jq -r '.status')
        detail=$(echo "$result" | jq -r '.detail')
        # Store in GITHUB_ENV
        echo "VALIDATE_STATUS=${status}" >> "$GITHUB_ENV"
        echo "VALIDATE_DETAIL={detail}" >> "$GITHUB_ENV"
