name: Validate template

description: Validate ADF template

inputs:
  path:
    required: true
    description: Project root
  directory:
    required: false
    description: Template directory

outputs:
  status:
    description: Validate status
    value: ${{ fromJSON(steps.validate-template.outputs.result).status }}
  detail:
    description: Validate detail
    value: ${{ fromJSON(steps.validate-template.outputs.result).detail }}

runs:
  using: composite
  steps:
    - name: Setup Deno environment
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Validate template
      id: validate-template
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        result=$(deno run --allow-read "${ACTION_PATH}/src/main.ts" "${INPUT_PATH}" "${INPUT_DIRECTORY}")
        echo "result=${result}" >> "$GITHUB_OUTPUT"
      shell: bash
